apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - music-collector-db-secret.yaml
  - music-collector-jwt-secret.yaml
  - music-collector-storage-secret.yaml
  - music-collector-oauth-secret.yaml
  - music-collector-mail-secret.yaml
  - music-collector-discogs-secret.yaml
  - music-collector-turnstile-secret.yaml
