---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: music-collector-apple-music-secret
  namespace: music-collector-staging
spec:
  encryptedData:
    MC_APPLE_PRIVATE_KEY: AgAbhriunIMGYUUVZbq6d5itbmiMYB43M7EmvVOaAFQsir3Dgx/Bz/eFYWzEvx7AnYYmzmbF0w6WO1ITBs5fmsdrQ8RZ+HYFbtt7iMWBVbu+nnGZ+O1WVo+3+qUfr7NS4+aOe+3GL5Dr3ovBYT5UxzaCjCnV71jBb0reZHXZE/s5ADEZepZPKDN9Jnl1sDpqrUyfjM936I924pCT5DcYQpLWAMfzzsMmYCU/h1Wq2fhn6NI6/sGJyKLPUGKr8nfxCwNOD+G5lo37f+Q1Ab3S7YtahniU6P9/P9JwfaAELThvSgAen0Vn9rSS2Vz1Q7ADbS1byUoV/YIHFog4au618Kth85TSd03KxmRnAWohXhyjrb622ra4c/eDT1RdyJqeLcetELIyJJrqXoe6ZuFwKcwRksRxAmYFxCQXSRhyhPA2QgdAk7PUXsCTiVXpWf9MGmRK45t1D9GCl8b9x4ZcNnIqf2IQEbiNA6z6g3KvkgTkcclbcLQX8OXZLBfcEYUy6HE9uBTJxhp5Uu0LTnetQh7SLx6BnaF2PZ8JYwi54xRFTN6CYyZu1iPNXEwJ8y6S7c1vn1srHU+inzSiADkZLt9B8oGRdixuaSYZXKTUQDVFuDbhJey3MgMJbwFV/GiM/v4yFS0O4iSgxCfkSb0grbab4F7So8+pgBt+Q9PomHNliavff8BHqu0mrwJ+939khRl5MVyGTnPinv3Bdt2jOB14+/NTk/MD8GzMRkx8AOyMJq1O30umKMxBGUgHH4G5M7zbqVvFx8XjAVfINZRRSA4r+js218k9QSVozEjbKonCHMnIGSYamhvxc8LaK6jtOveZVEllHb+I/nYr0e2UShEQp4y/c71duL+EM9sAIyIXR2lAdSAqBUD0MYd22aCSwyOfch1fDqBP/kmfvLkBhTuE/Szw44Gmv3TvXufL4DRZ2dqWMpsG3HoBYmS4ZSoxtYqOjHqyp3KRLlVNyeNtmE3vRFGEwAzVo6ynS/S6LxXAKJi2UG5cmLy0x+KrAawBFjsu9LJd88nv7po3ExKfzGyLiQ==
  template:
    metadata:
      name: music-collector-apple-music-secret
      namespace: music-collector-staging
