---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: music-collector-apple-music-secret
  namespace: music-collector-prod
spec:
  encryptedData:
    MC_APPLE_PRIVATE_KEY: AgBZI4f1FiSM65CxpVD4xjOmdCrmWHL7SW2DAFAFUlK3bJlBzbXkNIHvWkDskjy/EAN5sff1sj/uvFHyu8JOBd8xouSrJ4d5eSMb/9n6oSzFZ0MP5YFe20MTBDkFiSd9IH+vWhBdtEJAYL2XErhHcPP3pyZ/+GCB59JFIeL2OhMRIc2WubXOQ3UlUf21r99KwzEjsuO4ZSNJ2X4aae9SOcD5+mAdg8x9O5vCS/+9Z1fxs9QbFHMcSlEhQO2SEx/Lca6aIOvq2tEpqqQdDl7PCqODDHwhgk/pDoWPs4S35YIKuKy3A6e2Bl/gom/YNoEWaI2TJ2NUPy422hABsLr2a14Hx8uwykytLd6FhZSpg5bnn7kjCh5wMChTnuNSye3CKzaDxzpSX/g9+slQbSzk39b8iah8tbLYUas7X6Vs/Q71/wFAVESez1U/o0LndIG2awMEuXyhuFbCjUSbm0j6V65mWN3oHdRq6oLwXLTvI3SlKXW+4RF1OBDD9wuCHvLpxK+ECVdtvfxVI9vMqeQB/QJmboSq2x0wbdhC5JKNo6FZz0Yu8/C0yW2YvhTHaMcF2OvMhmsnU48s5k3+iWWWq/+zsqw+J1q329nMNbauT3mswUIFTD3zaxaNPNw6ku9yfO3t71FbMaW4B+8NulwkGZxvqttuwPiTQ+u94zriClZ6LLlSshqhDIWKyeKNo6ix1kt8GOoqKh3zOBccbcKDvsFdruCjzeO4DclOVLZ8kxmkNQofp1U3e1uZw7bbiab6jrksB9NB2s4gdmi/2MjPUQR23PXqIDaYcyo8BC1TissrthKkV9i9/OmPg8OqFg5EWNumLE0jsafDbO71kDxg+rB8/Z/yPbe3n6CkYXz7IW/DtkBmB3+AEvmTDe/9Yp8rzmy/VCrCuoNn6fAnid+cUN7yZ1OR3Gc0hwFYSuVSDXBWh1A75+94IG+++Bbpu12Rq/lLFSn1pRTjd+gbsU/K3aiMQ5srRFx1LpSOoCQf+62uEDBITFXH53EZhfqv46hthnkhqhixlElnHHQEBMxph81hXw==
  template:
    metadata:
      name: music-collector-apple-music-secret
      namespace: music-collector-prod
